sprites = {}
sprites.maps = {}
sprites.maps.test1 = love.graphics.newImage('sprites/maps/test1.png')
sprites.maps.test2 = love.graphics.newImage('sprites/maps/test2.png')
sprites.maps.test3 = love.graphics.newImage('sprites/maps/test3.png')
sprites.maps.test4 = love.graphics.newImage('sprites/maps/test4.png')
sprites.characters = {}
sprites.characters.unit = love.graphics.newImage('sprites/characters/unit.png')
sprites.characters.skull = love.graphics.newImage('sprites/characters/skull.png')
sprites.attacks = {}
sprites.attacks.laser = love.graphics.newImage('sprites/attacks/laser.png')
sprites.effects = {}
sprites.effects.enemyDestroy = love.graphics.newImage('sprites/effects/enemyDestroy.png')
sprites.effects.stars = love.graphics.newImage('sprites/effects/stars.png')
sprites.effects.stars2 = love.graphics.newImage('sprites/effects/stars2.png')
sprites.ui = {}
sprites.ui.arrowHead = love.graphics.newImage('sprites/ui/arrowHead.png')
sprites.ui.sidePanel = love.graphics.newImage('sprites/ui/sidePanel.png')
sprites.ui.coreHoverPanel = love.graphics.newImage('sprites/ui/coreHoverPanel.png')
sprites.ui.coreDiceIcons = love.graphics.newImage('sprites/ui/diceIcons.png')
sprites.ui.itemHoverPanel = love.graphics.newImage('sprites/ui/itemHoverPanel.png')
sprites.ui.dice = love.graphics.newImage('sprites/ui/dice.png')
sprites.ui.wrench = love.graphics.newImage('sprites/ui/wrench.png')
sprites.ui.battery = love.graphics.newImage('sprites/ui/battery.png')

fonts = {}
fonts.debug = love.graphics.newFont("fonts/vt323/VT323-Regular.ttf", 15*scale)
fonts.coreHover = love.graphics.newFont("fonts/kenney-pixel/Kenney-Pixel.ttf", 10*scale)
fonts.coreHoverTitle = love.graphics.newFont("fonts/kenney-pixel/Kenney-Pixel.ttf", 12*scale)
fonts.itemHover = love.graphics.newFont("fonts/kenney-pixel/Kenney-Pixel.ttf", 10*scale)

sounds = {}