waveData = {
    {
        {"skull", 2},
        {"skull", 2},
        {"skull", 0.75},
        {"skull", 0.75},
        {"skull", 0.75},
        {"skull", 2},
        {"skull", 1},
        {"skull", 3},
        {"fastSkull", 1},
        {"fastSkull", 1},
    },
    {
        {"skull", 1},
        {"skull", 2},
        {"skull", 0.75},
        {"skull", 0.75},
        {"skull", 0.75},
        {"skull", 2},
        {"skull", 1},
        {"skull", 0.75},
        {"skull", 0.75},
        {"skull", 0.75},
        {"skull", 0.75},
        {"skull", 3},
        {"skull", 0.75},
        {"skull", 2},
        {"skull", 1},
        {"skull", 0.75},
        {"skull", 0.75},
    },
    {
        {"skull", 1},
        {"skull", 2},
        {"skull", 0.75},
        {"skull", 0.75},
        {"skull", 0.75},
        {"skull", 2},
        {"fastSkull", 1},
        {"skull", 0.75},
        {"skull", 0.75},
        {"skull", 0.75},
        {"skull", 0.75},
        {"skull", 3},
        {"fastSkull", 0.75},
        {"skull", 2},
        {"skull", 3},
        {"fastSkull", 0.75},
        {"fastSkull", 0.75},
        {"fastSkull", 0.75},
        {"fastSkull", 0.75},
        {"fastSkull", 0.75},
        {"fastSkull", 0.75},
        {"fastSkull", 0.75},
        {"fastSkull", 0.75},
        {"fastSkull", 0.75},
        {"fastSkull", 0.75},
    },
    

}