waveData = {
    {
        {"skull", 2},
        {"skull", 2},
        {"skull", 0.75},
        {"skull", 0.75},
        {"skull", 0.75},
        {"skull", 2},
        {"skull", 1},
        {"skull", 3},
        {"fastSkull", 1},
        {"fastSkull", 1},
    },
    {
        {"skull", 1},
        {"skull", 2},
        {"skull", 0.75},
        {"skull", 0.75},
        {"skull", 0.75},
        {"skull", 2},
        {"skull", 1},
        {"skull", 0.75},
        {"skull", 0.75},
        {"skull", 0.75},
        {"skull", 0.75},
        {"skull", 3},
        {"skull", 0.75},
        {"skull", 2},
        {"skull", 1},
        {"skull", 0.75},
        {"skull", 0.75},
    },
    {
        {"skull", 1},
        {"skull", 2},
        {"skull", 0.75},
        {"skull", 0.75},
        {"skull", 0.75},
        {"skull", 2},
        {"fastSkull", 1},
        {"skull", 0.75},
        {"skull", 0.75},
        {"skull", 0.75},
        {"skull", 0.75},
        {"skull", 3},
        {"fastSkull", 0.75},
        {"skull", 2},
        {"skull", 3},
        {"fastSkull", 0.75},
        {"fastSkull", 0.75},
        {"fastSkull", 0.75},
        {"fastSkull", 0.75},
        {"fastSkull", 0.75},
        {"fastSkull", 0.75},
        {"fastSkull", 0.75},
        {"fastSkull", 0.75},
        {"fastSkull", 0.75},
        {"fastSkull", 0.75},
    },
    {
        {"squid", 1},
        {"squid", 2},
        {"skull", 0.75},
        {"skull", 0.75},
        {"skull", 0.75},
        {"skull", 2},
        {"squid", 1},
        {"skull", 0.75},
        {"skull", 0.75},
        {"skull", 0.75},
        {"skull", 0.75},
        {"squid", 3},
        {"fastSkull", 0.75},
        {"fastSkull", 2},
        {"fastSkull", 1},
        {"squid", 0.5},
        {"squid", 0.5},
        {"squid", 2},
        {"squid", 0.5},
        {"squid", 0.5},
        {"squid", 2},
        {"fastSkull", 0.75},
        {"fastSkull", 0.75},
        {"squid", 0.75},
        {"squid", 0.75},
    },
    {
        {"skull", 1},
        {"skull", 2},
        {"squid", 0.75},
        {"squid", 0.75},
        {"squid", 0.75},
        {"skull", 2},
        {"squid", 1},
        {"squid", 0.75},
        {"squid", 0.75},
        {"squid", 0.75},
        {"squid", 0.75},
        {"skull", 1},
        {"skull", 1},
        {"skull", 3},
        {"fastSquid", 1},
        {"fastSquid", 1},
        {"fastSquid", 1},
        {"squid", 0.5},
        {"squid", 0.5},
        {"skull", 2},
        {"skull", 0.5},
        {"skull", 0.5},
        {"squid", 3},
        {"fastSquid", 1},
        {"fastSkull", 1},
        {"fastSquid", 1},
        {"fastSkull", 1},
        {"fastSquid", 1},
        {"fastSkull", 1},
        {"fastSquid", 0.5},
        {"fastSkull", 0.5},
        {"fastSquid", 0.5},
        {"fastSkull", 0.5},
        {"fastSquid", 0.5},
        {"fastSkull", 0.5},
        {"fastSquid", 0.5},
    }
}